from __future__ import annotations

from datetime import UTC, datetime, timedelta
from decimal import Decimal

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.security import hash_password
from app.models.entities import Offer, PriceHistory, Product, Store, User
from app.services.matching import normalize_text

STORE_DATA = [
    {"slug": "demotech", "name": "DemoTech", "base_url": "https://example.com/demotech"},
    {"slug": "pc-market", "name": "PC Market", "base_url": "https://example.com/pc-market"},
    {
        "slug": "hardware-hub",
        "name": "Hardware Hub",
        "base_url": "https://example.com/hardware-hub",
    },
]


PRODUCT_DATA = [
    (
        "cpu",
        "AMD",
        "AMD Ryzen 5 5600",
        "CPU-R5-5600",
        479,
        125,
        70,
        35,
        75,
        {
            "socket": "AM4",
            "cores": 6,
            "threads": 12,
            "power_w": 88,
            "peak_power_w": 88,
            "overclockable": True,
        },
    ),
    (
        "cpu",
        "AMD",
        "AMD Ryzen 5 7600",
        "CPU-R5-7600",
        799,
        178,
        72,
        88,
        82,
        {
            "socket": "AM5",
            "cores": 6,
            "threads": 12,
            "power_w": 88,
            "peak_power_w": 88,
            "overclockable": True,
        },
    ),
    (
        "cpu",
        "AMD",
        "AMD Ryzen 7 7700",
        "CPU-R7-7700",
        1099,
        224,
        68,
        90,
        86,
        {
            "socket": "AM5",
            "cores": 8,
            "threads": 16,
            "power_w": 105,
            "peak_power_w": 142,
            "overclockable": True,
        },
    ),
    (
        "cpu",
        "Intel",
        "Intel Core i5-14400F",
        "CPU-I5-14400F",
        899,
        194,
        62,
        55,
        79,
        {
            "socket": "LGA1700",
            "cores": 10,
            "threads": 16,
            "power_w": 148,
            "peak_power_w": 148,
            "overclockable": False,
        },
    ),
    (
        "motherboard",
        "MSI",
        "MSI B550M PRO-VDH WIFI",
        "MB-B550M-VDH",
        429,
        35,
        65,
        35,
        76,
        {
            "socket": "AM4",
            "ram_type": "DDR4",
            "form_factor": "mATX",
            "m2_slots": 2,
            "m2_sizes": [2242, 2260, 2280],
            "m2_pcie_generation": 4,
            "sata_ports": 4,
            "wifi": True,
            "bluetooth": True,
            "ram_slots": 4,
            "max_ram_gb": 128,
            "max_ram_speed_mhz": 4400,
            "recommended_cpu_power_w": 145,
            "fan_headers": 3,
            "front_usb_c_header": False,
            "cpu_overclocking": True,
        },
    ),
    (
        "motherboard",
        "ASRock",
        "ASRock B650M-HDV/M.2",
        "MB-B650M-HDV",
        509,
        45,
        65,
        85,
        78,
        {
            "socket": "AM5",
            "ram_type": "DDR5",
            "form_factor": "mATX",
            "m2_slots": 2,
            "m2_sizes": [2280],
            "m2_pcie_generation": 5,
            "sata_ports": 4,
            "wifi": False,
            "bluetooth": False,
            "ram_slots": 2,
            "max_ram_gb": 96,
            "max_ram_speed_mhz": 6400,
            "recommended_cpu_power_w": 170,
            "fan_headers": 3,
            "front_usb_c_header": True,
            "cpu_overclocking": True,
        },
    ),
    (
        "motherboard",
        "MSI",
        "MSI B650 Gaming Plus WiFi",
        "MB-B650-GPW",
        719,
        58,
        74,
        92,
        88,
        {
            "socket": "AM5",
            "ram_type": "DDR5",
            "form_factor": "ATX",
            "m2_slots": 3,
            "m2_sizes": [2260, 2280],
            "m2_pcie_generation": 5,
            "sata_ports": 4,
            "wifi": True,
            "bluetooth": True,
            "ram_slots": 4,
            "max_ram_gb": 192,
            "max_ram_speed_mhz": 7200,
            "recommended_cpu_power_w": 230,
            "fan_headers": 6,
            "front_usb_c_header": True,
            "cpu_overclocking": True,
        },
    ),
    (
        "motherboard",
        "MSI",
        "MSI PRO B760M-A WIFI DDR4",
        "MB-B760M-A",
        649,
        48,
        70,
        54,
        82,
        {
            "socket": "LGA1700",
            "ram_type": "DDR4",
            "form_factor": "mATX",
            "m2_slots": 2,
            "m2_sizes": [2280],
            "m2_pcie_generation": 4,
            "sata_ports": 4,
            "wifi": True,
            "bluetooth": True,
            "ram_slots": 4,
            "max_ram_gb": 128,
            "max_ram_speed_mhz": 5333,
            "recommended_cpu_power_w": 190,
            "fan_headers": 4,
            "front_usb_c_header": True,
            "cpu_overclocking": False,
        },
    ),
    (
        "gpu",
        "AMD",
        "Radeon RX 7600 8GB",
        "GPU-RX7600",
        1099,
        198,
        65,
        45,
        72,
        {
            "gpu_brand": "AMD",
            "vram_gb": 8,
            "length_mm": 240,
            "height_mm": 120,
            "slots": 2.2,
            "power_w": 165,
            "peak_power_w": 190,
            "power_connectors": ["8-pin"],
            "recommended_psu_w": 550,
        },
    ),
    (
        "gpu",
        "NVIDIA",
        "GeForce RTX 4060 8GB",
        "GPU-RTX4060",
        1299,
        218,
        78,
        52,
        78,
        {
            "gpu_brand": "NVIDIA",
            "vram_gb": 8,
            "length_mm": 250,
            "height_mm": 125,
            "slots": 2.2,
            "power_w": 115,
            "peak_power_w": 140,
            "power_connectors": ["8-pin"],
            "recommended_psu_w": 550,
        },
    ),
    (
        "gpu",
        "AMD",
        "Radeon RX 7800 XT 16GB",
        "GPU-RX7800XT",
        2199,
        356,
        58,
        67,
        84,
        {
            "gpu_brand": "AMD",
            "vram_gb": 16,
            "length_mm": 280,
            "height_mm": 130,
            "slots": 2.7,
            "power_w": 263,
            "peak_power_w": 320,
            "power_connectors": ["8-pin", "8-pin"],
            "recommended_psu_w": 700,
        },
    ),
    (
        "gpu",
        "NVIDIA",
        "GeForce RTX 4070 SUPER 12GB",
        "GPU-RTX4070S",
        2699,
        402,
        72,
        72,
        88,
        {
            "gpu_brand": "NVIDIA",
            "vram_gb": 12,
            "length_mm": 261,
            "height_mm": 126,
            "slots": 2.5,
            "power_w": 220,
            "peak_power_w": 260,
            "power_connectors": ["12V-2x6"],
            "recommended_psu_w": 700,
            "requires_atx_3": True,
        },
    ),
    (
        "ram",
        "Kingston",
        "Kingston Fury Beast 32GB DDR4-3200",
        "RAM-KF-32-D4",
        259,
        55,
        90,
        35,
        82,
        {
            "ram_type": "DDR4",
            "capacity_gb": 32,
            "modules": 2,
            "speed_mhz": 3200,
            "height_mm": 34,
            "ecc": False,
        },
    ),
    (
        "ram",
        "Lexar",
        "Lexar Ares 32GB DDR5-6000",
        "RAM-LX-32-D5",
        419,
        78,
        88,
        82,
        86,
        {
            "ram_type": "DDR5",
            "capacity_gb": 32,
            "modules": 2,
            "speed_mhz": 6000,
            "height_mm": 43,
            "ecc": False,
        },
    ),
    (
        "ram",
        "Kingston",
        "Kingston Fury Beast 64GB DDR5-6000",
        "RAM-KF-64-D5",
        789,
        91,
        88,
        88,
        90,
        {
            "ram_type": "DDR5",
            "capacity_gb": 64,
            "modules": 2,
            "speed_mhz": 6000,
            "height_mm": 35,
            "ecc": False,
        },
    ),
    (
        "storage",
        "Lexar",
        "Lexar NM790 1TB NVMe",
        "SSD-NM790-1T",
        259,
        80,
        100,
        70,
        82,
        {
            "interface": "NVMe",
            "capacity_gb": 1000,
            "read_mbps": 7400,
            "form_factor": 2280,
            "pcie_generation": 4,
        },
    ),
    (
        "storage",
        "Lexar",
        "Lexar NM790 2TB NVMe",
        "SSD-NM790-2T",
        449,
        88,
        100,
        82,
        86,
        {
            "interface": "NVMe",
            "capacity_gb": 2000,
            "read_mbps": 7400,
            "form_factor": 2280,
            "pcie_generation": 4,
        },
    ),
    (
        "storage",
        "Samsung",
        "Samsung 990 PRO 2TB",
        "SSD-990PRO-2T",
        649,
        100,
        100,
        85,
        94,
        {
            "interface": "NVMe",
            "capacity_gb": 2000,
            "read_mbps": 7450,
            "form_factor": 2280,
            "pcie_generation": 4,
        },
    ),
    (
        "cooler",
        "Endorfy",
        "Endorfy Spartan 5",
        "COOL-SPARTAN5",
        109,
        38,
        72,
        50,
        76,
        {
            "type": "air",
            "sockets": ["AM4", "AM5", "LGA1700"],
            "cooling_capacity_w": 160,
            "height_mm": 146,
            "max_ram_height_mm": 45,
        },
    ),
    (
        "cooler",
        "Endorfy",
        "Endorfy Fortis 5",
        "COOL-FORTIS5",
        219,
        62,
        92,
        72,
        88,
        {
            "type": "air",
            "sockets": ["AM4", "AM5", "LGA1700"],
            "cooling_capacity_w": 220,
            "height_mm": 159,
            "max_ram_height_mm": 45,
        },
    ),
    (
        "cooler",
        "be quiet!",
        "be quiet! Dark Rock 5",
        "COOL-DR5",
        329,
        72,
        98,
        78,
        94,
        {
            "type": "air",
            "sockets": ["AM4", "AM5", "LGA1700"],
            "cooling_capacity_w": 260,
            "height_mm": 161,
            "max_ram_height_mm": 42,
        },
    ),
    (
        "case",
        "Endorfy",
        "Endorfy Ventum 200 Air",
        "CASE-VENTUM200",
        289,
        35,
        72,
        65,
        78,
        {
            "motherboard_form_factors": ["mATX", "ATX"],
            "max_gpu_length_mm": 315,
            "max_gpu_height_mm": 145,
            "max_gpu_slots": 3.5,
            "max_cooler_height_mm": 161,
            "psu_form_factors": ["ATX"],
            "max_psu_length_mm": 180,
            "radiator_support_mm": [120, 240, 280],
            "included_fans": 4,
            "fan_hub": False,
            "front_usb_c": False,
        },
    ),
    (
        "case",
        "Fractal",
        "Fractal Design Pop Air",
        "CASE-POPAIR",
        419,
        45,
        82,
        75,
        88,
        {
            "motherboard_form_factors": ["mATX", "ATX"],
            "max_gpu_length_mm": 405,
            "max_gpu_height_mm": 165,
            "max_gpu_slots": 4,
            "max_cooler_height_mm": 170,
            "psu_form_factors": ["ATX"],
            "max_psu_length_mm": 200,
            "radiator_support_mm": [120, 240, 280],
            "included_fans": 3,
            "fan_hub": False,
            "front_usb_c": False,
        },
    ),
    (
        "case",
        "be quiet!",
        "be quiet! Pure Base 500DX",
        "CASE-500DX",
        599,
        52,
        96,
        80,
        94,
        {
            "motherboard_form_factors": ["mATX", "ATX"],
            "max_gpu_length_mm": 369,
            "max_gpu_height_mm": 170,
            "max_gpu_slots": 4,
            "max_cooler_height_mm": 190,
            "psu_form_factors": ["ATX"],
            "max_psu_length_mm": 225,
            "radiator_support_mm": [120, 240, 280, 360],
            "included_fans": 3,
            "fan_hub": True,
            "front_usb_c": True,
        },
    ),
    (
        "psu",
        "MSI",
        "MSI MAG A650BN 650W",
        "PSU-A650BN",
        299,
        38,
        62,
        45,
        70,
        {
            "wattage": 650,
            "efficiency": "80+ Bronze",
            "connectors": ["8-pin", "8-pin"],
            "form_factor": "ATX",
            "length_mm": 140,
            "atx_3": False,
        },
    ),
    (
        "psu",
        "be quiet!",
        "be quiet! Pure Power 12 M 750W",
        "PSU-PP12-750",
        449,
        58,
        91,
        86,
        92,
        {
            "wattage": 750,
            "efficiency": "80+ Gold",
            "connectors": ["8-pin", "8-pin", "12V-2x6"],
            "form_factor": "ATX",
            "length_mm": 160,
            "atx_3": True,
        },
    ),
    (
        "psu",
        "Corsair",
        "Corsair RM850e 850W",
        "PSU-RM850E",
        559,
        66,
        93,
        92,
        94,
        {
            "wattage": 850,
            "efficiency": "80+ Gold",
            "connectors": ["8-pin", "8-pin", "8-pin", "12V-2x6"],
            "form_factor": "ATX",
            "length_mm": 140,
            "atx_3": True,
        },
    ),
]


async def seed_demo_data(session: AsyncSession) -> None:
    stores_by_slug: dict[str, Store] = {}
    for data in STORE_DATA:
        store = await session.scalar(select(Store).where(Store.slug == data["slug"]))
        if store is None:
            store = Store(**data, country="PL", parser_type="manual")
            session.add(store)
            await session.flush()
        stores_by_slug[store.slug] = store

    product_count = await session.scalar(select(func.count(Product.id))) or 0
    if product_count == 0:
        for index, row in enumerate(PRODUCT_DATA, start=1):
            category, brand, name, sku, base_price, performance, noise, upgrade, quality, specs = (
                row
            )
            product = Product(
                category=category,
                brand=brand,
                name=name,
                normalized_name=normalize_text(f"{brand} {name} {sku}"),
                sku=sku,
                mpn=sku,
                image_url=f"https://placehold.co/600x400?text={sku}",
                performance_score=performance,
                noise_score=noise,
                upgrade_score=upgrade,
                quality_score=quality,
                specs=specs,
            )
            session.add(product)
            await session.flush()
            variants = [
                ("demotech", Decimal(base_price), Decimal("0")),
                ("pc-market", Decimal(base_price) + Decimal("19.99"), Decimal("0")),
                ("hardware-hub", Decimal(base_price) - Decimal("10.00"), Decimal("14.99")),
            ]
            for offer_idx, (store_slug, price, shipping) in enumerate(variants, start=1):
                store = stores_by_slug[store_slug]
                offer = Offer(
                    product_id=product.id,
                    store_id=store.id,
                    external_id=f"{sku}-{offer_idx}",
                    title_raw=name,
                    url=f"{store.base_url}/{sku}?offer={offer_idx}",
                    price=price,
                    shipping_price=shipping,
                    currency="PLN",
                    in_stock=True,
                    stock_quantity=20,
                )
                session.add(offer)
                await session.flush()
                session.add(
                    PriceHistory(
                        offer_id=offer.id,
                        price=price,
                        shipping_price=shipping,
                        in_stock=True,
                        recorded_at=datetime.now(UTC) - timedelta(days=index % 7),
                    )
                )

    if settings.admin_bootstrap_email and settings.admin_bootstrap_password:
        email = settings.admin_bootstrap_email.lower()
        admin = await session.scalar(select(User).where(User.email == email))
        if admin is None:
            session.add(
                User(
                    email=email,
                    display_name="Administrator",
                    password_hash=hash_password(
                        settings.admin_bootstrap_password.get_secret_value()
                    ),
                    role="admin",
                    is_verified=True,
                )
            )
    await session.commit()
