"""initial production schema

Revision ID: b2cf229c705d
Revises: 
Create Date: 2026-07-12 21:42:45.805100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2cf229c705d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_rates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('quote', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base', 'quote', 'rate_date', name='uq_currency_rate_day')
    )
    op.create_index(op.f('ix_currency_rates_base'), 'currency_rates', ['base'], unique=False)
    op.create_index(op.f('ix_currency_rates_quote'), 'currency_rates', ['quote'], unique=False)
    op.create_index(op.f('ix_currency_rates_rate_date'), 'currency_rates', ['rate_date'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=120), nullable=False),
    sa.Column('ean', sa.String(length=32), nullable=True),
    sa.Column('mpn', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=1000), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('performance_score', sa.Float(), nullable=False),
    sa.Column('noise_score', sa.Float(), nullable=False),
    sa.Column('upgrade_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('specs', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ean')
    )
    op.create_index(op.f('ix_products_brand'), 'products', ['brand'], unique=False)
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index('ix_products_category_brand', 'products', ['category', 'brand'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    op.create_index(op.f('ix_products_mpn'), 'products', ['mpn'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_normalized_name'), 'products', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('service_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_service_tokens_token_hash'), 'service_tokens', ['token_hash'], unique=True)
    op.create_table('stores',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('parser_type', sa.String(length=40), nullable=False),
    sa.Column('parser_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_stores_is_active'), 'stores', ['is_active'], unique=False)
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('operation', sa.String(length=60), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error_type', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_created_at'), 'ai_usage', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_usage_operation'), 'ai_usage', ['operation'], unique=False)
    op.create_index(op.f('ix_ai_usage_provider'), 'ai_usage', ['provider'], unique=False)
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_service_token_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=120), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_service_token_id'], ['service_tokens.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('access_token_hash', sa.String(length=64), nullable=True),
    sa.Column('public_slug', sa.String(length=64), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('budget', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('total_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('store_count', sa.Integer(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_expires_at'), 'builds', ['expires_at'], unique=False)
    op.create_index(op.f('ix_builds_is_saved'), 'builds', ['is_saved'], unique=False)
    op.create_index(op.f('ix_builds_owner_id'), 'builds', ['owner_id'], unique=False)
    op.create_index('ix_builds_owner_saved', 'builds', ['owner_id', 'is_saved'], unique=False)
    op.create_index(op.f('ix_builds_profile'), 'builds', ['profile'], unique=False)
    op.create_index(op.f('ix_builds_public_slug'), 'builds', ['public_slug'], unique=True)
    op.create_index(op.f('ix_builds_visibility'), 'builds', ['visibility'], unique=False)
    op.create_table('favorite_products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_favorite_product')
    )
    op.create_index(op.f('ix_favorite_products_product_id'), 'favorite_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_favorite_products_user_id'), 'favorite_products', ['user_id'], unique=False)
    op.create_table('offers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title_raw', sa.String(length=1000), nullable=True),
    sa.Column('url', sa.String(length=1500), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_id', 'external_id', name='uq_offer_store_external')
    )
    op.create_index(op.f('ix_offers_currency'), 'offers', ['currency'], unique=False)
    op.create_index(op.f('ix_offers_fetched_at'), 'offers', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_offers_in_stock'), 'offers', ['in_stock'], unique=False)
    op.create_index(op.f('ix_offers_is_active'), 'offers', ['is_active'], unique=False)
    op.create_index(op.f('ix_offers_product_id'), 'offers', ['product_id'], unique=False)
    op.create_index('ix_offers_product_stock_currency', 'offers', ['product_id', 'in_stock', 'currency'], unique=False)
    op.create_index(op.f('ix_offers_store_id'), 'offers', ['store_id'], unique=False)
    op.create_table('one_time_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_one_time_tokens_expires_at'), 'one_time_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_one_time_tokens_purpose'), 'one_time_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_one_time_tokens_token_hash'), 'one_time_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_one_time_tokens_user_id'), 'one_time_tokens', ['user_id'], unique=False)
    op.create_index('ix_ott_user_purpose', 'one_time_tokens', ['user_id', 'purpose'], unique=False)
    op.create_table('parser_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parser_runs_status'), 'parser_runs', ['status'], unique=False)
    op.create_index(op.f('ix_parser_runs_store_id'), 'parser_runs', ['store_id'], unique=False)
    op.create_index(op.f('ix_parser_runs_task_id'), 'parser_runs', ['task_id'], unique=False)
    op.create_table('product_benchmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('workload', sa.String(length=120), nullable=False),
    sa.Column('resolution', sa.String(length=30), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=500), nullable=True),
    sa.Column('measured_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'workload', 'resolution', name='uq_benchmark')
    )
    op.create_index(op.f('ix_product_benchmarks_product_id'), 'product_benchmarks', ['product_id'], unique=False)
    op.create_index(op.f('ix_product_benchmarks_workload'), 'product_benchmarks', ['workload'], unique=False)
    op.create_table('build_components',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('selected_offer_id', sa.Uuid(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['selected_offer_id'], ['offers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'category', name='uq_build_category')
    )
    op.create_index(op.f('ix_build_components_build_id'), 'build_components', ['build_id'], unique=False)
    op.create_index(op.f('ix_build_components_category'), 'build_components', ['category'], unique=False)
    op.create_index(op.f('ix_build_components_product_id'), 'build_components', ['product_id'], unique=False)
    op.create_table('build_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('build_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('build_id', 'revision', name='uq_build_revision')
    )
    op.create_index(op.f('ix_build_revisions_build_id'), 'build_revisions', ['build_id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('shipping_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_offer_id'), 'price_history', ['offer_id'], unique=False)
    op.create_index('ix_price_history_offer_recorded', 'price_history', ['offer_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_price_history_recorded_at'), 'price_history', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_recorded_at'), table_name='price_history')
    op.drop_index('ix_price_history_offer_recorded', table_name='price_history')
    op.drop_index(op.f('ix_price_history_offer_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_build_revisions_build_id'), table_name='build_revisions')
    op.drop_table('build_revisions')
    op.drop_index(op.f('ix_build_components_product_id'), table_name='build_components')
    op.drop_index(op.f('ix_build_components_category'), table_name='build_components')
    op.drop_index(op.f('ix_build_components_build_id'), table_name='build_components')
    op.drop_table('build_components')
    op.drop_index(op.f('ix_product_benchmarks_workload'), table_name='product_benchmarks')
    op.drop_index(op.f('ix_product_benchmarks_product_id'), table_name='product_benchmarks')
    op.drop_table('product_benchmarks')
    op.drop_index(op.f('ix_parser_runs_task_id'), table_name='parser_runs')
    op.drop_index(op.f('ix_parser_runs_store_id'), table_name='parser_runs')
    op.drop_index(op.f('ix_parser_runs_status'), table_name='parser_runs')
    op.drop_table('parser_runs')
    op.drop_index('ix_ott_user_purpose', table_name='one_time_tokens')
    op.drop_index(op.f('ix_one_time_tokens_user_id'), table_name='one_time_tokens')
    op.drop_index(op.f('ix_one_time_tokens_token_hash'), table_name='one_time_tokens')
    op.drop_index(op.f('ix_one_time_tokens_purpose'), table_name='one_time_tokens')
    op.drop_index(op.f('ix_one_time_tokens_expires_at'), table_name='one_time_tokens')
    op.drop_table('one_time_tokens')
    op.drop_index(op.f('ix_offers_store_id'), table_name='offers')
    op.drop_index('ix_offers_product_stock_currency', table_name='offers')
    op.drop_index(op.f('ix_offers_product_id'), table_name='offers')
    op.drop_index(op.f('ix_offers_is_active'), table_name='offers')
    op.drop_index(op.f('ix_offers_in_stock'), table_name='offers')
    op.drop_index(op.f('ix_offers_fetched_at'), table_name='offers')
    op.drop_index(op.f('ix_offers_currency'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_favorite_products_user_id'), table_name='favorite_products')
    op.drop_index(op.f('ix_favorite_products_product_id'), table_name='favorite_products')
    op.drop_table('favorite_products')
    op.drop_index(op.f('ix_builds_visibility'), table_name='builds')
    op.drop_index(op.f('ix_builds_public_slug'), table_name='builds')
    op.drop_index(op.f('ix_builds_profile'), table_name='builds')
    op.drop_index('ix_builds_owner_saved', table_name='builds')
    op.drop_index(op.f('ix_builds_owner_id'), table_name='builds')
    op.drop_index(op.f('ix_builds_is_saved'), table_name='builds')
    op.drop_index(op.f('ix_builds_expires_at'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_provider'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_operation'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_created_at'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_index(op.f('ix_stores_is_active'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_service_tokens_token_hash'), table_name='service_tokens')
    op.drop_table('service_tokens')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_normalized_name'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_mpn'), table_name='products')
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index('ix_products_category_brand', table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.drop_index(op.f('ix_products_brand'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_currency_rates_rate_date'), table_name='currency_rates')
    op.drop_index(op.f('ix_currency_rates_quote'), table_name='currency_rates')
    op.drop_index(op.f('ix_currency_rates_base'), table_name='currency_rates')
    op.drop_table('currency_rates')
    # ### end Alembic commands ###
