"""refresh token replay protection

Revision ID: f3aec9117641
Revises: 16aeded06a84
Create Date: 2026-07-12 21:54:24.118357

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f3aec9117641"
down_revision: Union[str, Sequence[str], None] = "16aeded06a84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refresh_token_history",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("rotated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["auth_sessions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_refresh_token_history_rotated_at"),
        "refresh_token_history",
        ["rotated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_token_history_session_id"),
        "refresh_token_history",
        ["session_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_refresh_token_history_token_hash"),
        "refresh_token_history",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        op.f("ix_refresh_token_history_user_id"), "refresh_token_history", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refresh_token_history_user_id"), table_name="refresh_token_history")
    op.drop_index(op.f("ix_refresh_token_history_token_hash"), table_name="refresh_token_history")
    op.drop_index(op.f("ix_refresh_token_history_session_id"), table_name="refresh_token_history")
    op.drop_index(op.f("ix_refresh_token_history_rotated_at"), table_name="refresh_token_history")
    op.drop_table("refresh_token_history")
    # ### end Alembic commands ###
